### PR TITLE
Add option to change eSCO Transport Unit Size to 16

### PR DESCRIPTION
**Pull request by Specter421**
* Fixes bluetooth calls in many samsung devices

[SamarV-121: Make it conditional and apply it for mSBC T1, CVSD codec as well]

### CODE REVIEW

**Comment by gwolf2u** [comment]
how does this affect other devices?

**Comment by Specter421** [comment]
> how does this affect other devices?

It doesn't change anything unless you add "#define BTM_ESCO_TRANSPORT_UNIT_SIZE_PCM16" in "bdroid_buildcfg.h" in device tree... and only Samsung devices needs that... to be more precise, it won't affect other devices. also sorry for my bad english :D

**Comment by neobuddy89** [comment]
We are not tracking system/bt in crdroid. @gwolf2u

**Comment by gwolf2u** [comment]
awww... didn't check indeed

**Pull request merged**
